[target.aarch64-linux-android]
ar = "workspace/abe/measurement_client_rust/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "workspace/abe/measurement_client_rust/NDK/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "workspace/abe/measurement_client_rust/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "workspace/abe/measurement_client_rust/NDK/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "workspace/abe/measurement_client_rust/NDK/x86/bin/i686-linux-android-ar"
linker = "workspace/abe/measurement_client_rust/NDK/x86/bin/i686-linux-android-clang"